# strings methods
name = 'durgesh shARma Is a gOod boY?'
print(name.upper())
print(name.lower())
print(name.islower())
print(name.isupper())
print(name.swapcase())
print(name.isalnum())
print(name.isalpha())
print(name.isprintable())
print(name.istitle())
print(name.isspace())
print(name.count('A'))
print(len(name))
print(name.split('Is'))
print(name.replace("shARma", "DIKSHA"))
print(name.title())
print(name.endswith("?"))
print(name.center(50,"."))
print(name.capitalize())
print(name.find('O'))
print(name.rstrip("boY?"))
print(name.rsplit("boY?"))
print(name.encode())
print(name.startswith("dsad"))
# print(name.lstrip('Is'))                          ## need to check